### Obtener todos los usuarios
GET http://localhost:8000/Usuario

###

### Crear nuevo usuario
POST http://localhost:8000/Usuario
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "email": "juan@mail.com",
  "password": "123456",
  "telefono": "3001234567",
  "direccion": "Calle 123",
  "id_ciudad": 1,
  "rol": "admin"
}

###

### Editar un usuario existente
PUT http://localhost:8000/Usuario
Content-Type: application/json

{
  "id_usuario": 3,
  "nombre": "Juan Perez",
  "email": "juan@mail.com",
  "password": "654321",
  "telefono": "3109876543",
  "direccion": "Av Siempre Viva",
  "id_ciudad": 2,
  "rol": "productor"
}

###

### Eliminar un usuario por ID
DELETE http://localhost:8000/Usuario/2


//___________//_____________//________________//____________________//____________________
###login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "email": "juan@mail.com",
  "password": "123456789"
}

//___________//_____________//________________//____________________//____________________
### Obtener un producto por ID
GET http://localhost:8000/productos

### Agregar un nuevo producto
POST http://localhost:8000/productos
Content-Type: application/json

{
  "nombre": "Tomates Cherry",
  "descripcion": "Tomates cherry frescos y organicos",
  "precio": 4.2,
  "stock": 50,
  "stockMinimo": 10,
  "id_usuario": 1,
  "id_ciudad_origen": 1,
  "unidadMedida": "kg",
  "pesoAprox": 0.02,
  "imagenData": "file:///C:/Users/jbarr/Pictures/"
}

### Editar un producto existente

PUT http://localhost:8000/productos/7
Content-Type: application/json

{
  "nombre": "Manzanas Verdes Premium",
  "descripcion": "Manzanas verdes premium de alta calidad",
  "precio": 4.5,
  "stock": 80,
  "stockMinimo": 20,
  "id_usuario": 1,
  "id_ciudad_origen": 1,
  "unidadMedida": "kg",
  "pesoAprox": 0.18,
  "imagenData": "file:///C:/Users/jbarr/Pictures/"
}

### Eliminar un producto por ID
DELETE http://localhost:8000/productos/7


//___________//_____________//________________//____________________//____________________

### Obtener todas las regiones
GET http://localhost:8000/regiones

### Agregar una nueva region
POST http://localhost:8000/regiones
Content-Type: application/json

{
  "nombre": "Region Andina"
}

### Editar una region existente
PUT http://localhost:8000/regiones
Content-Type: application/json

{
  "id_region": 7,
  "nombre": "Region Editada"
}



### Eliminar una region por ID
DELETE http://localhost:8000/regiones/7

//___________//_____________//________________//____________________//____________________
### Obtener todos los departamentos
GET http://localhost:8000/departamentos

### Agregar un nuevo departamento
POST http://localhost:8000/departamentos
Content-Type: application/json

{
  "nombre": "Departamento de Prueba",
  "id_region": 1
}

### Editar un departamento existente
PUT http://localhost:8000/departamentos
Content-Type: application/json

{
  "id_departamento": 34,
  "nombre": "Departamento Editado",
  "id_region": 2
}

### Eliminar un departamento por ID
DELETE http://localhost:8000/departamentos/34

//___________//_____________//________________//____________________//____________________

### Obtener todas las ciudades
GET http://localhost:8000/ciudades

### Agregar una nueva ciudad
POST http://localhost:8000/ciudades
Content-Type: application/json

{
  "nombre": "Ciudad de Prueba",
  "id_departamento": 1
}

### Editar una ciudad existente
PUT http://localhost:8000/ciudades
Content-Type: application/json

{
  "id_ciudad": 33,
  "nombre": "Ciudad Editada",
  "id_departamento": 2
}

### Eliminar una ciudad por ID
DELETE http://localhost:8000/ciudades/33


//___________//_____________//________________//____________________//____________________

###obtener todas las alertas
GET http://localhost:8000/alertas

### Obtener alertas activas (ultimos 7 dias)
GET http://localhost:8000/alertas/activas

### Generar alertas automaticas
POST http://localhost:8000/alertas/generar
Content-Type: application/json

###

### Marcar alerta como resuelta (cambiar el ID por uno existente)
PUT http://localhost:8000/alertas/1/resolver
Content-Type: application/json
###

### Eliminar una alerta por ID (cambiar el ID por uno existente)
DELETE http://localhost:8000/alertas/2

//___________//_____________//________________//____________________//____________________

### Obtener todos los detalles de pedidos
GET http://localhost:8000/detalle_pedidos

### Agregar un nuevo detalle de pedido
POST http://localhost:8000/detalle_pedidos
Content-Type: application/json

{
  "id_pedido": 1,
  "id_producto": 2,
  "cantidad": 85,
  "precio_unitario": 3.500,
  "precio_total": 297500
}

### Eliminar un detalle de pedido por ID
DELETE http://localhost:8000/detalle_pedidos/1



//___________//_____________//________________//____________________//____________________

### Obtener todas las reseñas
GET http://localhost:8000/resenas

### Agregar una nueva reseña
POST http://localhost:8000/resenas
Content-Type: application/json

{
  "id_producto": 10,
  "id_pedido": 5,
  "comentario": "Excelente productp esta en perfecto estado",
  "calificacion": 5,
  "fecha": "2025-09-18"
}

### Editar una reseña existente
PUT http://localhost:8000/resenas
Content-Type: application/json

{
  "id_resena": 7,
  "id_producto": 10,
  "id_pedido": 5,
  "comentario": "El producto es bueno pero tardo en llegar",
  "calificacion": 4,
  "fecha": "2025-09-18"
}

### Eliminar una reseña por ID
DELETE http://localhost:8000/resenas/7

//___________//_____________//________________//____________________//____________________
### Obtener todos los consejos
GET http://localhost:8000/Consejo

###

### Crear nuevo consejo
POST http://localhost:8000/Consejo
Content-Type: application/json

{
  "id_usuario": 2,
  "titulo": "Consejo para sembrar tomates",
  "contenido": "Usa abono orgánico y riega temprano en la mañana para mejores resultados.",
  "fecha": "2025-09-18"
}

###

### Editar un consejo existente
PUT http://localhost:8000/Consejo
Content-Type: application/json

{
  "id_consejo": 3,
  "id_usuario": 1,
  "titulo": "Consejo actualizado para sembrar tomates",
  "contenido": "Mantén el suelo húmedo pero evita el exceso de agua.",
  "fecha": "2025-09-18"
}

###

### Eliminar un consejo por ID
DELETE http://localhost:8000/Consejo/2
